# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CommonAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'RxAlamofire'
  pod 'RxOptional'
  pod 'Action'
  pod 'NSObject+Rx'

  # Pods for CommonAPI

  target 'CommonAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CommonAPIUITests' do
    # Pods for testing
  end

end
